warnings_are_errors: false

language: r

cache: packages

sudo: false

r:
  - bioc-devel

branches:
  only:
    - master
    - RELEASE_3_7

bioc_packages:
  - HelloRanges
  - HelloRangesData
  - BSgenome.Hsapiens.UCSC.hg19

r_packages:
  - rlang
  - dplyr
  - magrittr
  - ggplot2
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
